spring.application.name: LiquibaseAplication
spring:
   datasource:
       url: jdbc:postgresql://localhost:5432/liquibase_example@localhost
       username: postgres
       driver-class-name: org.postgresql.Driver
       password: 1234
   liquibase:
      change-log: classpath:db/changelog/db.changelog-master.xml